- server/lib/genome/importers/file_importers/cgi.rb
Fixing a few small issues in CGI data as they come up
> Fix: CGI data cleaning

- server/lib/genome/groupers/base.rb
- server/lib/genome/groupers/drug_grouper.rb
- server/lib/genome/groupers/gene_grouper.rb
- server/lib/tasks/groupers.rake
> feat: import normalizer data as individual sources

- server/lib/genome/importers/file_importers/chembl.rb
adding in a few other data points (withdrawn flag, unlinked drug terms for search purposes)
> feat: add additional chembl data

- server/lib/genome/importers/file_importers/drugbank.rb
- server/lib/genome/importers/file_importers/nci.rb
- server/lib/tasks/importers.rake
- server/lib/utils/pmid.rb
ran through every source this weekend to see what was still needed -- made a few small changes to get rake tasks working for imports
> fix: make rake import tasks work

- .github/workflows/branch_workflow_rules.yaml
- .github/workflows/close_issue.yaml
* add test that PRs into `main` come from `staging`, and that PRs into `staging` come from `dev`
* add action that closes related issues when PRs are merged to `dev`
> ci: add workflow helpers

- server/lib/genome/importers/file_importers/nci.rb
- server/lib/tasks/importers.rake
> Do something about the volume of NCI records

- server/lib/genome/importers/api_importers/pharos/api_client.rb
- server/lib/genome/importers/api_importers/pharos/importer.rb
> Removed counts from ApiClient as it was making GET request timeout

- .github/workflows/deploy_client.yaml
- client/.env.production
- server/lib/genome/groupers/drug_grouper.rb
> Fix merge conflicts

- server/lib/genome/importers/api_importers/jax_ckb/api_client.rb
- server/lib/tasks/importers.rake
> feat: add jax ckb importer

- client/src/components/Browse/Sources/BrowseSources.scss
- client/src/components/Browse/Sources/BrowseSources.tsx
- client/src/components/Drug/DrugSummary/DrugSummary.scss
- client/src/components/Drug/DrugSummary/DrugSummary.tsx
- client/src/components/Gene/GeneSummary/GeneSummary.scss
- client/src/components/Gene/GeneSummary/GeneSummary.tsx
- client/src/components/Layout/MainLayout.scss
- client/src/pages/Results/Results.tsx
> Styling fixes

- client/src/components/Drug/DrugSummary/DrugSummary.scss
- client/src/components/Drug/DrugSummary/DrugSummary.tsx
- client/src/components/Gene/GeneCharts/RegulatoryApprovalGene.tsx
- client/src/components/Gene/GeneSummary/GeneSummary.scss
- client/src/components/Gene/GeneSummary/GeneSummary.tsx
- client/src/components/Layout/MainLayout.scss
> Infographics updates

- client/src/components/Shared/SearchBar/SearchBar.tsx
- client/yarn.lock
> Clear all search button

- client/src/pages/About/About.scss
> Text color on about page

- client/src/components/Drug/DrugRecord/DrugRecord.tsx
- client/src/components/Drug/DrugTable/DrugTable.scss
- client/src/components/Drug/DrugTable/DrugTable.tsx
- client/src/components/Gene/GeneIntTable/GeneIntTable.tsx
- client/src/components/Gene/GeneRecord/GeneRecord.tsx
- client/src/index.css
- client/src/pages/Home/Home.scss
> Table link styling and functionality

- server/Gemfile
- server/Gemfile.lock
- server/lib/genome/groupers/drug_grouper.rb
- server/lib/genome/groupers/gene_grouper.rb
A semi-recent VRSATILE update altered a couple of the property names in the normalizer responses. This catches us up to that change.
> fix: update normalizer API

- server/lib/genome/importers/api_importers/civic/importer.rb
> fix: capture DRUG RESISTANCE category for CIViC genes

- server/lib/genome/importers/api_importers/civic/api_client.rb
- server/lib/genome/importers/api_importers/civic/importer.rb
> fix: handle civic api update

- client/src/components/Drug/DrugRecord/DrugRecord.scss
- client/src/components/Drug/DrugRecord/DrugRecord.tsx
- client/src/components/Gene/GeneRecord/GeneRecord.scss
- client/src/components/Gene/GeneRecord/GeneRecord.tsx
- client/src/hooks/queries/useGetDrugRecord.ts
- client/src/hooks/queries/useGetGeneRecord.ts
- client/src/hooks/queries/useGetInteractions.ts
- client/src/index.css
- server/app/graphql/resolvers/genes.rb
- server/app/graphql/types/gene_type.rb
- server/app/graphql/types/queries/gene_lookup_query.rb
- server/app/graphql/types/query_type.rb
- server/spec/factories/drug.rb
- server/spec/factories/gene.rb
- server/spec/queries/drug_query_spec.rb
- server/spec/queries/gene_concept_id_query_spec.rb
- server/spec/queries/gene_query_spec.rb
Close #253 
- Fix graphql definitions to make sure gene concept IDs are exposed correctly
- Add a lil concept ID subheader to gene/drug records
> feat: add concept ID to gene/drug record

- client/src/components/Drug/DrugRecord/DrugRecord.tsx
- client/src/hooks/queries/useGetInteractions.ts
- server/spec/queries/drug_interaction_query_spec.rb
closes #276 
Added sources/pmid retrieval to gql query and added back these fields to the individual record page.
> Fix drugs record table

- client/src/components/Drug/DrugSummary/DrugSummary.tsx
- client/src/components/Drug/DrugTable/DrugTable.tsx
- client/src/components/Gene/GeneIntTable/GeneIntTable.tsx
- client/src/components/Gene/GeneSummary/GeneSummary.tsx
- client/src/components/Shared/AmbiguousTermsSummary/AmbiguousResult.tsx
- client/src/components/Shared/AmbiguousTermsSummary/AmbiguousTerms.scss
- client/src/components/Shared/AmbiguousTermsSummary/AmbiguousTermsSummary.tsx
- client/src/hooks/queries/useGetAmbiguousResults.ts
- client/src/pages/Results/Results.tsx
> Drug ambiguous matches UI

- client/src/components/Shared/AmbiguousTermsSummary/AmbiguousResult.tsx
- client/src/components/Shared/AmbiguousTermsSummary/AmbiguousTermsSummary.tsx
- client/src/components/Shared/SearchBar/SearchBar.tsx
- client/src/pages/Home/Home.tsx
- client/src/pages/Results/Results.tsx
- client/src/providers/app.tsx
- client/src/routes/index.tsx
- client/src/routes/public.tsx
closes #201 
This PR introduces search persistence so a user does not need to re-submit their search after visiting a record page or refreshing on the results page
> Search persistence

- client/src/components/Drug/DrugRecord/DrugRecord.tsx
- client/src/hooks/queries/useGetDrugRecord.ts
- server/spec/factories/drug_application.rb
- server/spec/queries/drug_query_spec.rb
close #254 
- the "launch" link icon is slightly off center and I don't know why; we should fix it when we do the style review of the page (sorry for causing more problems)
- it would be great to add popups describing approval status (maybe with links back to descriptions on source pages) in a future issue
> feat: add approval tables to drug record

- client/src/components/Gene/Categories/CategoryResults.scss
- client/src/pages/About/About.scss
- client/src/pages/Downloads/Downloads.scss
This PR fixes a few misc styling issues across pages.
**gene category search**: 
- Changed result text colors to black for better readability
**about page**: 
- Fixed a spacing issue in acknowledgements section
- Added padding between sections for readability
**downloads page**:
- Added padding between sections for readability
> More scss changes

- client/src/pages/Results/Results.tsx
added logic to only modify search terms based on params if they don't exist in the state
closes #325
> fixing bug where search terms would get duplicated

- client/src/components/Interaction/InteractionRecord/InteractionRecord.scss
- client/src/components/Interaction/InteractionRecord/InteractionRecord.tsx
- server/lib/genome/importers/file_importers/cgi.rb
> fix: limit interaction attribute height

- client/src/components/Interaction/InteractionRecord/InteractionRecord.scss
- client/src/components/Interaction/InteractionRecord/InteractionRecord.tsx
> feat: add links to interaction record page

- server/lib/genome/importers/file_importers/cgi.rb
> fix: handle messy CGI drug class names

- client/src/components/Gene/GeneCharts/RegulatoryApprovalGene.tsx
- client/src/hooks/queries/useGetAmbiguousResults.ts
- server/spec/queries/gene_matches_query_spec.rb
> fix: make sure drug approval ratings are queried in search page

- server/lib/genome/groupers/base.rb
> fix: use vote-counting to handle ambiguous drug/gene grouping

- client/src/index.css
- client/src/pages/About/About.scss
- client/src/pages/About/SubSections/Contact.tsx
- client/src/pages/About/SubSections/Overview.tsx
- client/src/pages/About/SubSections/Publications.tsx
Make link content and styling on about page more consistent, including addressing request to make citation in overview a link
> cleanup: make about links consistent

- server/lib/genome/importers/file_importers/guide_to_pharmacology.rb
- server/lib/genome/names.rb
> fix: clean up GtoP import

- server/lib/genome/importers/api_importers/go/api_client.rb
> fix: use latest GO address

- server/lib/genome/importers/file_importers/drugbank.rb
still need to figure out a solution that doesn't involve setting it manually
> feat: bump drugbank version

- client/src/components/Browse/Sources/BrowseSources.tsx
> feat: alphabetize sources

- client/src/components/Shared/InteractionTable/InteractionTable.tsx
> Issue 435: fix pmid/source sorting

- client/src/components/Interaction/InteractionRecord/InteractionRecord.tsx
- client/src/hooks/queries/useGetInteractionRecord.ts
> feat: add sources to interaction page

- client/src/components/Interaction/InteractionRecord/InteractionRecord.tsx
> feat: reduce precision of interaction score

- client/src/components/Shared/SearchBar/SearchBar.tsx
> feat: add support for pasting terms into the search bar

- client/src/pages/About/SubSections/Overview.tsx
* Update citation given at top of about page
* Update item counts
> docs: update overview

- server/app/graphql/resolvers/genes.rb
> feat: make gene claim category search case-insensitive

- server/lib/genome/importers/api_importers/jax_ckb/api_client.rb
close #520 
also make error message a little more descriptive
> fix: update JAX-CKB URL

- server/lib/genome/importers/file_importers/chembl.rb
this wasn't working for some reason
> fix: chembl version

- server/app/graphql/types/query_type.rb
> fix: remove redundant field

- .github/workflows/build_client.yml
- .github/workflows/deploy.yml
- .github/workflows/test_client.yaml
- .github/workflows/test_server.yaml
actions are starting to get some warnings about this
> cicd: update actions revs

- README.md
- server/lib/tasks/importers.rake
* correct data normalizer command in README
* add print message to GtoP importer
> chore: fix a couple of typos/omissions

- client/src/pages/Downloads/Files/Files.tsx
Adding new rows to the data table to support 2024 tsv releases
> add rows for Download table for 2024 tsvs

- client/src/components/Browse/Sources/BrowseSources.tsx
- client/src/hooks/queries/useGetDruggableSources.ts
- server/lib/genome/importers/api_importers/ckb_core/importer.rb
- server/lib/genome/importers/file_importers/caris_molecular_intelligence.rb
* fix URLs - close #560 
* correct CKB url
* links open in new tab
> fix: resolve source URLs

- server/lib/genome/groupers/drug_grouper.rb
- server/lib/genome/groupers/gene_grouper.rb
> fix: use correct logging method

- server/app/controllers/counts_controller.rb
- server/config/routes.rb
close #597 
it's cheap to compute so I figure invalidating the cache daily is fine
@mcannon068nw let me know if you want any other things tallied here
> feat: add stats api endpoint
