server/lib/genome/importers/base.rb
Close #79 
* Adds some extra logging for the thing I was thinking of (how invalid interaction claim types/gene categories are caught)
=> Feat: Catch invalid claim types/categories with logging, not exceptions

server/app/graphql/types/directionality_type.rb, server/app/graphql/types/interaction_claim_type_type.rb
close #97 
I think this is the correct way to do this (@acoffman)?
Also, it looks to me like "directionality unclear" isn't used by any importers, maybe delete?
=> fix: correct directionality enum mapping for graphql

server/lib/genome/importers/file_importers/oncokb.rb, server/lib/genome/importers/file_importers/oncokb.sql
As far as I can tell, OncoKB no longer provides an endpoint that lists every curated variant and drug annotation. Until that changes, or we figure out what I'm missing, I've manually dumped the OncoKB data from the v4 database into some CSVs (see provided SQL queries file) and written up a quick importer to pull them in.
Close #47
=> feat: add oncokb "importer"

.github/workflows/deploy_client.yaml, .github/workflows/test_client_build.yaml
Upgrade actions/checkout to v3 to silence warning about deprecated node version
=> ci: use latest checkout version

server/app/graphql/types/drug_application_type.rb, server/app/graphql/types/drug_approval_rating_type.rb, server/app/graphql/types/query_type.rb
fixes #218 
Fixed a few fields on `DrugApplicationType` and `DrugApprovalRatingType` and made them available as top level queries.
I should note that I did not need to make any changes to the code to get the fields to return values with the example query provided in #218
=> Expose additional fields

server/app/models/drug_claim.rb, server/lib/genome/importers/base.rb, server/lib/genome/importers/file_importers/drugbank.rb
closes #142 
I have fixed the problem of the drugbank importer creating DrugClaims and GeneClaims with blank names and InteractionClaimAttributes with blank values.
The blank name for DrugClaims was a result of a flag in the xml parser incorrectly getting flipped to true. The other two cases were due to not having checks for when their tags of interest were blank. 
This PR adds a validation to the name field on DrugClaim, and changes `first_or_create` to `first_or_create!` in /lib/genome/importers/base.rb for the `create_drug_claim` method. We might also want to consider adding validations to the other fields affected by this issue. If that's desired, I can updated this PR or create a new issue and add it there.
=> Fixed DrugBank Importer Fetching Blank Values

server/app/controllers/graphql_controller.rb, server/app/graphql/resolvers/genes.rb, server/app/graphql/types/gene_match_type.rb, server/app/graphql/types/queries/gene_lookup_query.rb, server/app/graphql/types/query_type.rb, server/db/migrate/20230104221712_add_indexes.rb
After playing with a couple of different implementations, this seems like the best approach to power the type of UI we want, but I'm obviously open to feedback!
Essentially now it will be a two query approach. First there is a new `geneMatches` query that takes search terms. This will take your search terms and perform the bucketing into direct, ambiguous, and unmatched terms. From this response you can retrieve the search terms, what type of match they were, and what genes they matched. Most importantly you can get a list of gene IDs.
The `genes` query now optionally accepts a list of Gene IDs as an argument in addition to the existing filters and automatically paginates.
In this way you can imagine running the initial query, getting two lists of gene ids, and then each tab can hit the …
=> Add Query For Ambiguous Matches

server/app/graphql/types/drug_alias_type.rb, server/app/graphql/types/drug_claim_alias_type.rb, server/app/graphql/types/gene_alias_type.rb, server/app/graphql/types/gene_claim_alias_type.rb
Make these things go away:
```
DrugAlias's `field :alias` conflicts with a built-in method, use `resolver_method:` to pick a different resolver method for this field (for example, `resolver_method: :resolve_alias` and `def resolve_alias`). Or use `method_
conflict_warning: false` to suppress this warning.
```
=> refactor: use resolver method to avoid namespace collisions for :alias

server/lib/genome/importers/api_importers/civic/api_client.rb, server/lib/genome/importers/api_importers/civic/importer.rb
Per #265  -- temporarily(?) don't import any molecular profiles that contain multiple variations
=> fix: temporarily block complex molecular profiles in CIViC

server/app/graphql/resolvers/drugs.rb, server/app/graphql/types/drug_match_type.rb, server/app/graphql/types/gene_match_type.rb, server/app/graphql/types/queries/drug_lookup_query.rb, server/app/graphql/types/query_type.rb, server/app/graphql/types/search_match_type.rb, server/spec/queries/drug_matches_query_spec.rb
Essentially identical to the Gene matching query, run one query to bucket the search terms into match types and get the IDs of the matched drugs, then query the `drugs` endpoint with the list of IDs.
Example query:
```
{
drugMatches(searchTerms: ["SUNITINIB", "ZALCITABINE", "LINCOCIN", "TRASTUZUMAB", "PHLORETIN", "NOTREAL"]) {
directMatches {
searchTerm
matches {
id
name
}
}
ambiguousMatches {
searchTerm
matches {
id
name
}
}
noMatches {
searchTerm
}
}
}
```
=> Add drug name matching query

server/lib/genome/importers/api_importers/pharos/api_client.rb, server/lib/genome/importers/api_importers/pharos/importer.rb
close #270 
fortunately, it appears that we don't have to use the janky receding-query trick to avoid request timeouts anymore
=> fix: update Pharos graphql query

client/src/hooks/queries/useGetInteractions.ts, server/spec/queries/drug_interaction_query_spec.rb, server/spec/queries/gene_interaction_query_spec.rb
interaction record page PR adds in routes to access interactions via: /interactions/<interaction_id>
This PR adds the <id> field to the hook used for drug and gene interactions (with tests added as well). I think theoretically this now will allow us to make interaction results clickable and directly link MUI TableRows to these records via that ID field (ala: https://stackoverflow.com/questions/50691049/how-to-add-link-react-router-per-each-material-ui-tablerow)
or I think you mentioned datagrid was being used, so potentially this: https://codesandbox.io/s/67252192react-material-ui-data-grid-add-link-z3izj?file=/demo.tsx
=> Add id to interaction hook

client/src/components/Browse/Sources/BrowseSources.scss, client/src/components/Browse/Sources/BrowseSources.tsx, client/src/hooks/queries/useGetDruggableSources.ts, client/src/pages/Downloads/SubSections/Info.tsx, server/spec/queries/sources_queries_spec.rb
closes #309 
This PR makes a couple of small miscellaneous changes for the information pages:
- sources versioning: versioning has been added per source (tests updated to match)
- hyperlink sources: source headers now hyperlink out to their respective sites (tests updated to match)
- downloads: instructions for loading the v5 database have been updated, as well as a link to sql data dump
=> Misc static info changes

client/src/components/Drug/DrugTable/DrugTable.tsx, client/src/components/Gene/Categories/CategoryResults.tsx, client/src/components/Gene/GeneIntTable/GeneIntTable.tsx, client/src/components/Shared/TableDownloader/TableDownloader.tsx, server/app/controllers/application_controller.rb, server/app/controllers/graphql_controller.rb, server/app/controllers/table_download_controller.rb, server/app/graphql/resolvers/genes.rb, server/app/graphql/types/gene_type.rb, server/app/models/gene.rb, server/app/tsv_exporters/drug_interactions_tsv.rb, server/app/tsv_exporters/gene_categories_tsv.rb, server/app/tsv_exporters/gene_interactions_tsv.rb, server/config/routes.rb
This introduces a new API endpoint and corresponding React component that allows for a user to download a data TSV based on the current parameters used in a query.
I wanted to get feedback on the approach before hooking it up to every table. It also will require some visual polish, I'm not sure how to constrain the size of the MUI loading spinner or error banner, so the button increases in size when either is present. (And the `LoadingButton` appears to be in beta/not shipped with the default library)
The `<TableDownloader/>` component takes two props: `tableName` which is the name of the table you want to download. This is registered in the  `table_resolvers` dictionary in the table downloads controller server side.
This determines which `Resolver` will get used to generate the TSV. …
=> TSV Downloads of Table Contents

client/src/pages/Playground/Playground.tsx
this PR adds example queries for pagination in graphql using the drugs and gene endpoints. Highlights the use of before and after with cursors to paginate.
(am also open to better/additional examples of pagination if this method doesn't work)
=> More example queries

server/app/graphql/resolvers/drugs.rb, server/app/graphql/resolvers/genes.rb
This PR resolves an issue found regarding resolvers joining redundant rows when filters are utilized.
Example case:
```
{
genes(names: ["BCL2","ABL1","PDGFRA"]) {
nodes {
name
interactions {
drug {
name
conceptId
}
interactionScore
interactionTypes {
type
directionality
}
interactionAttributes {
name
value
}
publications {
pmid
}
sources {
sourceDbName
}
}
}
}
}
```
returns 212 results
```
{
genes(names: ["BCL2","ABL1","PDGFRA"], sourceDbName: "NCI") {
nodes {
name
interactions {
drug {
name
conceptId
}
interactionScore
interactionTypes {
type
directionality
}
interactionAttributes {
name
value
}
publications {
pmid
}
sources {
sourceDbName
}
}
}
}
}
```
returns 4962 results
=> fix: Resolvers distinct fix

client/src/components/Drug/DrugRecord/DrugRecord.scss, client/src/components/Drug/DrugRecord/DrugRecord.tsx, client/src/components/Gene/GeneRecord/GeneRecord.scss, client/src/components/Gene/GeneRecord/GeneRecord.tsx, client/src/utils/generateXrefLink.tsx
If an alias looks like a URI, try to generate a hyperlink out to the source page if it matches patterns for known resources.
It'd be great to restrict this behavior to a separate xrefs box on the drug/gene pages, but I think this is a good start
=> feat: provide hyperlinks to resources from xrefs

server/lib/genome/importers/api_importers/civic/importer.rb
Tiny fix, but with reason:
* in v4, we used gene symbols for gene claim names from CIViC. I think we switched for v5 because the CIViC API refers to the full name as `officialName`, and that sounds very official. But the Gene Normalizer can't currently search full names (we should probably fix this?), and anyway, we typically try to use the symbol for the claim name in all other sources.
* Incidentally, this would also fix our KRAS/NRAS problem.
=> fix: use symbol for CIViC gene claim name

server/lib/genome/importers/file_importers/caris_molecular_intelligence.rb, server/lib/genome/importers/file_importers/cgi.rb, server/lib/genome/importers/file_importers/dtc.rb, server/lib/genome/importers/file_importers/foundation_one_genes.rb, server/lib/genome/importers/file_importers/pharmgkb.rb
We were using the current date to set the version for a number of sources that are actually static imports (I think this was my bad). I went back and grabbed the date set in dgidb v4.
=> fix: correct source versioning

client/src/components/Shared/SearchBar/SearchBar.tsx
=> fix: do not allow search submit if no terms entered

client/src/pages/Downloads/Info/Info.tsx, server/lib/tasks/db_bootstrapping.rake, server/lib/utils/snapshot_helpers.rb
Updated the dgidb:load_local method with the new hosted file location. Running the following rake task while inside the server directory should download the file and instantiate a local db:
`rake dgidb:load_local`
=> Update dgidb:load_local method

client/src/components/Browse/Sources/BrowseSources.scss, client/src/components/Drug/DrugRecord/DrugRecord.scss, client/src/components/Drug/DrugRecord/DrugRecord.tsx, client/src/components/Drug/DrugSummary/DrugSummary.scss, client/src/components/Drug/DrugSummary/DrugSummary.tsx, client/src/components/Gene/GeneRecord/GeneRecord.scss, client/src/components/Gene/GeneRecord/GeneRecord.tsx, client/src/components/Gene/GeneSummary/GeneSummary.scss, client/src/components/Gene/GeneSummary/GeneSummary.tsx, client/src/components/GeneCategories/AmbiguousMatchCard/AmbiguousMatchCard.tsx, client/src/components/Interaction/InteractionRecord/InteractionRecord.tsx, client/src/components/Layout/MainLayout.tsx, client/src/components/Shared/AmbiguousTermsSummary/AmbiguousTerms.scss, client/src/components/Shared/AmbiguousTermsSummary/AmbiguousTermsSummary.tsx, client/src/components/Shared/InteractionTable/InteractionTable.tsx, client/src/components/Shared/SearchBar/SearchBar.tsx, client/src/components/Shared/TabPanel/TabPanel.tsx, client/src/hooks/shared/useGetIsMobile.tsx, client/src/pages/About/About.tsx, client/src/pages/Home/Home.scss, client/src/routes/public.tsx, client/tsconfig.json
Opening this draft PR to help me keep track of my progress and what I still need to do. 
This PR will close #461 
Done so far:
- added hook to return boolean value if a screen size we consider "mobile" size is used
- made nav menu hamburger menu on small screen sizes + added a drawer and icons
- fixed majority of issues on the gene, drug, and interaction pages (stack each component vertically at 100% width)
- made components on home page not go off-screen 
- home page
- fixed bug where search results were getting repeated (not mobile-specific but needed a bandaid)
- point to ES6 because it's superior
- fixed about page (added floating button to jump between sections for mobile)
- browse sources - changed grid population to only display as many cards as possible given the space, otherwise …
=> feat: make app more mobile friendly 

client/src/pages/About/SubSections/Publications.tsx
Adding the v5 citation to the Publications section of the About page.
=> Update citations with V5 citation

server/app/graphql/resolvers/drugs.rb
closes #476 
The previous version was using `IN` and passing an array which will exact match. Unfortunately, as far as I'm aware, there is no equivalent `ILIKE IN` so we need to build the query up manually.
`Array.new(size, value)` initializes a new array of strings with the value `'name ILIKE ?'` equivalent to the number of drug names passed in.
`value.map {|v| "#{v}%"}` tacks on the `%` for left anchored wildcard matching to each search term, and then the `*` splats those terms out into parameters to the `where` clause. So you end up with something that will look like
`scope.where("name ILIKE ? OR name ILIKE ?", 'foo', 'bar')`. This allows us to dynamically build the query while still using ActiveRecord's built in query parameterization/escaping.
=> Use case insensitive, left anchored matching for drug names 

client/src/pages/Downloads/Files/Files.tsx
close #474 
Unsure how to test this locally?
=> fix: categories.tsv was downloading interactions

client/src/pages/About/SubSections/Contact.tsx, server/app/graphql/types/meta_type.rb, server/app/graphql/types/organization_type.rb, server/app/graphql/types/query_type.rb, server/app/graphql/types/service_type.rb, server/app/models/github_release.rb, server/config/initializers/dataset_version.rb, server/data_version.yml
This adds an initializer in `config/initializers` that will run at boot. It expects to find a `data_version.yml` at the root dir of the application. That file should contain a key `version` containing the current data version.
This will be loaded into a constant.
When generating a new data release, you will need to remember to update this value (so, if there are docs for the process somewhere, may be good to add this step to them). Its manual for now, but as we automate the data generation process, we should automate this too.
Additionally, I have added a top level `serviceInfo` query to the API containing all the fields needed for the [GA4GH Service discovery spec](https://editor.swagger.io/?url=https://raw.githubusercontent.com/ga4gh-discovery/ga4gh-service-info/develop/service-info.yaml …
=> Add support for GA4GH service info query

server/lib/genome/importers/api_importers/civic/api_client.rb, server/lib/genome/importers/api_importers/civic/importer.rb, server/lib/genome/names.rb
* Fix API breakage from latest CIViC GraphQL schema update
* Rewrite query strategy to first capture all drugs/genes, then all available interactions between them, rather than only importing drugs/genes that are involved in predictive statements. This enables us to eg link out to more CIViC entities than we would otherwise.
=> fix: use latest CIViC GraphQL API and capture all genes

client/src/pages/Downloads/Files/Files.tsx
Adds a new row to the downloads table for the last Dec 2023 dumps. New TSVs have been provided to @acoffman that will replace the latest row, and what was in the latest row previously will go to the new Dec 2023 row.
=> added row for Dec 2023 dumps

server/app/graphql/types/interaction_type.rb, server/app/models/interaction.rb, server/db/migrate/20240826185158_add_score_components.rb, server/db/structure.sql, server/lib/genome/groupers/interaction_grouper.rb
=> feat: store score components in DB

server/app/controllers/graphql_controller.rb, server/app/lib/api_analytics_tracer.rb
The intention here is that we can tell if `dgipy` is being used to issue requests against the API
=> feat: log API client

server/lib/tasks/db_bootstrapping.rake, server/lib/utils/snapshot_helpers.rb
* add a rake task to load DB w/ local sql dump
* remove rake task to download from remote. It depends on a static s3://<wagner bucket>/dgidb/dgidb_latest.sql URI and I'm not really happy with maintaining that. I'd rather have a better way of dynamically pointing to the latest-dated dump. Also, I thought some of the data was supposed to be private but I could be wrong.
* slightly reconfigure the section for psql executable injection into the PATH. Drop macports support. Add homebrew (ARM64) support.
=> feat: rake task to load DB from local file

server/Gemfile, server/Gemfile.lock, server/app/controllers/concerns/analytics.rb, server/config/environments/development.rb, server/config/environments/production.rb, server/config/environments/test.rb, server/config/puma.rb, server/spec/rails_helper.rb, server/spec/requests/graphql_spec.rb
Add simple tests for successful server response to requests made to the GraphQL API.
Slightly modified tracer configs to use a Ruby environment config rather than check directly for the environment. This value is temporarily changed in the request test but otherwise unaltered.
=> test: add basic API tests

server/lib/genome/importers/api_importers/civic/api_client.rb
This utilizes a new filter added in griffithlab/civic-v2#1212 to exclude Therapies from import unless they have at least one linked, non-rejected Evidence Item or Assertion.
We won't be able to deploy it until the referenced PR is merged and deployed in CIViC; I will follow up here when it is.
closes #576 
(Test failure is the result of the filter not existing on the prod CIViC schema yet)
=> Exclude unused CIViC Therapies

server/lib/genome/importers/api_importers/civic/api_client.rb
The ruby graphql client library generally recommends parsing queries against the schema at boot to avoid runtime errors and ensure you're not accepting arbitrary user injected strings (https://github.com/github-community-projects/graphql-client/blob/master/guides/dynamic-query-error.md). 
This unfortunately adds a boot-time dependency on connecting to the CIViC instance to retrieve the schema. The recommended workaround in the README is to include a static JSON dump of the schema in the app: https://github.com/github-community-projects/graphql-client?tab=readme-ov-file#configuration. This seems like it would be a pain point, having to keep this file up-to-date every time we make a change to the CIViC schema.
Given that these are not user-input queries but internally created for the …
=> fix: Lazy load CIViC GraphQL queries
